version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'

  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
    depends_on:
      - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

volumes:
  sqlserverdata:
